name: Deploy to Amazon EC2

on:
    push:
        branches: ["main"]

jobs:
    build:
        name: Build and deploy
        runs-on: ubuntu-latest
        steps:
            
            - name: Checkout repository
              uses: actions/checkout@v4

            - name: Set AWS credentials
              uses: aws-actions/configure-aws-credentials@v4
              with:
                aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
                aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
                aws-region: ${{ secrets.AWS_REGION }}
                
            - name: build node.js
              uses: actions/setup-node@v4
              with:
                node-version: "20.x"

            - run: npm i
            - run: npm run build

            - name: Run CodeDeploy
              run: |
                aws deploy create-deployment --application-name ${{ env.codedeployname }}-${{ env.environment }} --deployment-group-name ${{ env.codedeployname }}-${{ env.environment }} --deployment-config-name CodeDeployDefault.OneAtATime --github-location repository=${{ github.repository }},commitId=${{ github.sha }}
            

            